language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements_examples.txt
  - python setup.py install
# command to run tests
script:
  - python -m unittest discover .
