name: Unittests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r requirements_examples.txt
    - name: Run unittests
      run: |
        python -m unittest discover .
